language: objective-c

install:
  
  # lix
  - npm i haxeshim -g
  - npm i switchx -g
  - switchx install latest
  - npm i lix.pm -g
  
  # haxelib for hxcpp
  - cd ..
  - mkdir haxelib
  - haxelib setup haxelib
  - cd $TRAVIS_BUILD_DIR
  
  # libs
  - lix download
  
  # Build HXCPP
  - LIX_HXCPP=$(node cdFile.js haxe_libraries/hxcpp.hxml)
  - cd $LIX_HXCPP
  - haxelib dev hxcpp $LIX_HXCPP
  - cd $LIX_HXCPP/tools/hxcpp
  - haxe compile.hxml
  - cd $LIX_HXCPP/tools/build
  - haxe compile.hxml
  - cd $LIX_HXCPP/project
  - neko build.n
   
before_script:
script: